"""
Django settings for devadmin project.
Generated by 'django-admin startproject' using Django 4.2.7.
"""

import os
import secrets
from decouple import config
from pathlib import Path
import dj_database_url

# ==================== CONFIGURAÇÕES BÁSICAS ====================

# Diretório base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# ==================== SEGURANÇA ====================

# SECRET_KEY - CORREÇÃO CRÍTICA
# Primeiro tenta do .env, depois gera automaticamente
SECRET_KEY = config('SECRET_KEY', default='')

# **ADICIONE ESTAS 3 LINHAS:**
# Garante que SECRET_KEY tenha pelo menos 50 caracteres
if SECRET_KEY and (len(SECRET_KEY) < 50 or SECRET_KEY.startswith('django-insecure-')):
    import secrets
    SECRET_KEY = secrets.token_urlsafe(50)
    print(f"⚠️  SECRET_KEY reforçada para 50 caracteres")

if not SECRET_KEY:
    # Se não tiver SECRET_KEY, gera uma
    if 'RENDER' in os.environ:
        # Em produção, usa variável de ambiente
        SECRET_KEY = os.environ.get('SECRET_KEY', secrets.token_urlsafe(50))
    else:
        # Em desenvolvimento, gera e salva no .env
        SECRET_KEY = secrets.token_urlsafe(50)
        print(f"⚠️  SECRET_KEY gerada automaticamente. Adicione ao .env:")
        print(f"SECRET_KEY={SECRET_KEY}")

# DEBUG
DEBUG = config('DEBUG', default=True, cast=bool)

# Se estiver no Render, força DEBUG=False
if 'RENDER' in os.environ:
    DEBUG = False

# Domínios permitidos
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com', 'projeto-habitus.onrender.com']

# Adiciona hosts do .env
env_hosts = config('ALLOWED_HOSTS', default='')
if env_hosts:
    ALLOWED_HOSTS.extend([h.strip() for h in env_hosts.split(',')])

# Adiciona host do Render
if 'RENDER_EXTERNAL_HOSTNAME' in os.environ:
    ALLOWED_HOSTS.append(os.environ['RENDER_EXTERNAL_HOSTNAME'])

# ==================== CSRF CONFIGURATION ====================

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://localhost:8000',
    'https://127.0.0.1:8000',
    'https://habitus-2025.onrender.com',
    'https://habitus-cnat.vercel.app'
]

# Adiciona host do Render
if 'RENDER_EXTERNAL_HOSTNAME' in os.environ:
    render_host = os.environ['RENDER_EXTERNAL_HOSTNAME']
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_host}')

# ==================== MIDDLEWARE - CORREÇÃO DO CSRF ====================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # ← ESTA LINHA É ESSENCIAL
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

# ==================== CONFIGURAÇÕES DE SEGURANÇA ====================

# Configurações para produção
if not DEBUG:
    # Força HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS
    SECURE_HSTS_SECONDS = 31536000  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookies seguros
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Outras proteções
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # Desenvolvimento
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

# Configurações comuns
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False

# ==================== APLICAÇÕES ====================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'habitusapp'
]

# ==================== TEMPLATES ====================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ROOT_URLCONF = 'devadmin.urls'
WSGI_APPLICATION = 'devadmin.wsgi.application'
ASGI_APPLICATION = 'devadmin.asgi.application'

# ==================== BANCO DE DADOS ====================

# Banco de dados
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR}/db.sqlite3',
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# ==================== SENHAS ====================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==================== ARQUIVOS ESTÁTICOS ====================

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = BASE_DIR / 'staticfiles'
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

# ==================== AUTENTICAÇÃO ====================

LOGIN_REDIRECT_URL = '/feed/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/'

# ==================== INTERNACIONALIZAÇÃO ====================

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# ==================== FINAL ====================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    }
