# Generated by Django 4.2.7 on 2025-06-18 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="devadmin/static/videos-exercicios/",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "grupo_muscular",
                    models.CharField(
                        choices=[
                            ("Peito", "Peito"),
                            ("Ombro", "Ombro"),
                            ("Biceps", "Biceps"),
                            ("Dorsal", "Dorsal"),
                            ("Triceps", "Triceps"),
                            ("Quadriceps", "Quadriceps"),
                            ("Glúteos", "Glúteos"),
                            ("Isquiotibiais", "Isquiotibiais"),
                            ("Panturrilha", "Panturrilha"),
                            ("Abdominais", "Abdominais"),
                        ],
                        default="Peito",
                        max_length=20,
                    ),
                ),
                (
                    "dificuldade",
                    models.CharField(
                        choices=[
                            ("Iniciante", "Iniciante"),
                            ("Intermediário", "Intermediário"),
                            ("Avançado", "Avançado"),
                        ],
                        default="Iniciante",
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Treino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("quant_exercicios", models.IntegerField()),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "matricula",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "foto_perfil",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="devadmin/static/foto-perfil-professor/",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nasc", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "inst_formacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_admissao", models.DateField()),
                (
                    "tipo_trabalho",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Estágiario(a)", "Estágiario(a)"),
                            ("Professor(a)", "Professor(a)"),
                            ("Administrador(a)", "Administrador(a)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "matricula",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "foto_perfil",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="devadmin/static/foto-perfil-usuario/",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nasc", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("peso", models.FloatField(blank=True, null=True)),
                ("altura", models.FloatField(blank=True, null=True)),
                (
                    "nivel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Iniciante", "Iniciante"),
                            ("Intermediário", "Intermediário"),
                            ("Avançado", "Avançado"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ganho de Massa", "Ganho de Massa"),
                            ("Perda de peso", "Perda de peso"),
                            ("Saúde", "Saúde"),
                            ("Outro", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "matricula",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "foto_perfil",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="devadmin/static/foto-perfil-usuario/",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nasc", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_admissao", models.DateField()),
                (
                    "tipo_trabalho",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Estágiario(a)", "Estágiario(a)"),
                            ("Professor(a)", "Professor(a)"),
                            ("Administrador(a)", "Administrador(a)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("peso", models.FloatField(blank=True, null=True)),
                ("altura", models.FloatField(blank=True, null=True)),
                (
                    "nivel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Iniciante", "Iniciante"),
                            ("Intermediário", "Intermediário"),
                            ("Avançado", "Avançado"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ganho de Massa", "Ganho de Massa"),
                            ("Perda de peso", "Perda de peso"),
                            ("Saúde", "Saúde"),
                            ("Outro", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
