# Generated by Django 4.2.7 on 2025-06-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="foto_perfil",
            field=models.FileField(
                blank=True, null=True, upload_to="devadmin/static/foto-perfil-admin/"
            ),
        ),
    ]
