# Generated by Django 4.2.7 on 2025-06-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0002_alter_admin_foto_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="foto_perfil",
            field=models.ImageField(
                blank=True, null=True, upload_to="foto_perfil_admin/"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="foto_perfil",
            field=models.ImageField(
                blank=True, null=True, upload_to="foto_perfil_aluno/"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="foto_perfil",
            field=models.ImageField(
                blank=True, null=True, upload_to="foto_perfil_professor/"
            ),
        ),
    ]
