# Generated by Django 4.2.7 on 2025-06-22 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0004_alter_admin_foto_perfil_alter_aluno_foto_perfil_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "data_publicacao",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("AVISO IMPORTANTE", "Aviso Importante"),
                            ("INFORMAÇÃO", "Informação"),
                            ("OUTRO", "Outro"),
                        ],
                        default="INFORMAÇÃO",
                        max_length=20,
                    ),
                ),
                ("autor_nome", models.CharField(max_length=100)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="noticias/"),
                ),
            ],
        ),
    ]
