# Generated by Django 4.2.7 on 2025-06-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0005_noticia"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="autor_foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="foto-perfil-noticia/"
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="autor_tipo",
            field=models.CharField(default="admin", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="noticia",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
