# Generated by Django 4.2.7 on 2025-06-22 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habitusapp", "0006_noticia_autor_foto_noticia_autor_tipo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticia",
            name="autor_foto",
        ),
        migrations.AddField(
            model_name="noticia",
            name="autor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
