# Generated by Django 4.2.7 on 2025-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0007_remove_noticia_autor_foto_noticia_autor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="abdomen",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="abdominal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="axilar_media",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="braco_direito",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="braco_esquerdo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="cintura",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="coxa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="coxa_direita",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="coxa_esquerda",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="panturrilha",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="panturrilha_direita",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="panturrilha_esquerda",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="quadril",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="subescapular",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="suprailiaca",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="torax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="tricipital",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="abdomen",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="abdominal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="axilar_media",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="braco_direito",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="braco_esquerdo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="cintura",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="coxa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="coxa_direita",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="coxa_esquerda",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="panturrilha",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="panturrilha_direita",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="panturrilha_esquerda",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="quadril",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="subescapular",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="suprailiaca",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="torax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="tricipital",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="abdomen",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="abdominal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="axilar_media",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="braco_direito",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="braco_esquerdo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="cintura",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="coxa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="coxa_direita",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="coxa_esquerda",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="panturrilha",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="panturrilha_direita",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="panturrilha_esquerda",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="quadril",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="subescapular",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="suprailiaca",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="torax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="tricipital",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
