# Generated by Django 4.2.7 on 2025-06-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "habitusapp",
            "0008_admin_abdomen_admin_abdominal_admin_axilar_media_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="tipo_trabalho",
            field=models.CharField(
                choices=[
                    ("Professor(a)", "Professor(a)"),
                    ("Administrador(a)", "Administrador(a)"),
                ],
                max_length=20,
            ),
        ),
    ]
