# Generated by Django 4.2.7 on 2025-06-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0009_alter_professor_tipo_trabalho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticia",
            name="titulo",
        ),
        migrations.AlterField(
            model_name="noticia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("AVISO IMPORTANTE", "Aviso Importante"),
                    ("ALERTA", "Alerta"),
                    ("INFORMAÇÃO", "Informação"),
                    ("FUNCIONAMENTO", "Funcionamento"),
                    ("OUTRO", "Outro"),
                ],
                default="INFORMAÇÃO",
                max_length=20,
            ),
        ),
    ]
