# Generated by Django 4.2.7 on 2025-06-28 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habitusapp", "0013_alter_admin_tipo_trabalho_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treino",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="treino",
            name="quant_exercicios",
            field=models.IntegerField(editable=False),
        ),
        migrations.CreateModel(
            name="TreinoExercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.PositiveIntegerField(default=0)),
                ("repeticoes", models.PositiveIntegerField(default=0)),
                ("carga", models.CharField(blank=True, max_length=20, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "exercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habitusapp.exercicio",
                    ),
                ),
                (
                    "treino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercicios_treino",
                        to="habitusapp.treino",
                    ),
                ),
            ],
        ),
    ]
