# Generated by Django 4.2.7 on 2025-07-19 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habitusapp", "0014_treino_usuario_alter_treino_quant_exercicios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treino",
            name="nivel",
            field=models.CharField(
                choices=[("I", "Iniciante"), ("M", "Intermediário"), ("A", "Avançado")],
                default="I",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="treino",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
