# Generated by Django 4.2.7 on 2025-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0016_notificacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="data_admissao",
        ),
        migrations.AddField(
            model_name="treino",
            name="quant_treinos",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="professor",
            name="cpf",
            field=models.CharField(editable=False, max_length=14, unique=True),
        ),
    ]
