# Generated by Django 4.2.7 on 2025-08-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0017_remove_admin_data_admissao_treino_quant_treinos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treino",
            name="progresso_geral",
            field=models.IntegerField(default=0),
        ),
    ]
