# Generated by Django 5.2.4 on 2025-08-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0018_treino_progresso_geral"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treino",
            name="progresso_geral",
        ),
    ]
