# Generated by Django 5.2.4 on 2025-08-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0019_remove_treino_progresso_geral"),
    ]

    operations = [
        migrations.AddField(
            model_name="treino",
            name="progresso_geral",
            field=models.IntegerField(default=0),
        ),
    ]
