# Generated by Django 5.2.4 on 2025-09-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0021_remove_treino_progresso_geral"),
    ]

    operations = [
        migrations.AddField(
            model_name="treinoexercicio",
            name="concluido",
            field=models.BooleanField(default=False),
        ),
    ]
