# Generated by Django 5.2.4 on 2025-09-11 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0022_treinoexercicio_concluido"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="abdomen",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="abdominal",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="altura",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="axilar_media",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="braco_direito",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="braco_esquerdo",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="cintura",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="coxa",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="coxa_direita",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="coxa_esquerda",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="nivel",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="objetivo",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="panturrilha",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="panturrilha_direita",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="panturrilha_esquerda",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="peso",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="quadril",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="subescapular",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="suprailiaca",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="torax",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="tricipital",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="abdomen",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="abdominal",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="altura",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="axilar_media",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="braco_direito",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="braco_esquerdo",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="cintura",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="coxa",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="coxa_direita",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="coxa_esquerda",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="nivel",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="objetivo",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="panturrilha",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="panturrilha_direita",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="panturrilha_esquerda",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="peso",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="quadril",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="subescapular",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="suprailiaca",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="torax",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="tricipital",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="abdomen",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="abdominal",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="altura",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="axilar_media",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="braco_direito",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="braco_esquerdo",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="cintura",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="coxa",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="coxa_direita",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="coxa_esquerda",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="nivel",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="objetivo",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="panturrilha",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="panturrilha_direita",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="panturrilha_esquerda",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="peso",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="quadril",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="subescapular",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="suprailiaca",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="torax",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="tricipital",
        ),
        migrations.CreateModel(
            name="Progresso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peso", models.FloatField(blank=True, null=True)),
                ("altura", models.FloatField(blank=True, null=True)),
                (
                    "nivel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Iniciante", "Iniciante"),
                            ("Intermediário", "Intermediário"),
                            ("Avançado", "Avançado"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ganho de Massa", "Ganho de Massa"),
                            ("Perda de peso", "Perda de peso"),
                            ("Saúde", "Saúde"),
                            ("Outro", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("cintura", models.FloatField(blank=True, null=True)),
                ("abdomen", models.FloatField(blank=True, null=True)),
                ("torax", models.FloatField(blank=True, null=True)),
                ("quadril", models.FloatField(blank=True, null=True)),
                ("coxa_direita", models.FloatField(blank=True, null=True)),
                ("coxa_esquerda", models.FloatField(blank=True, null=True)),
                ("panturrilha_direita", models.FloatField(blank=True, null=True)),
                ("panturrilha_esquerda", models.FloatField(blank=True, null=True)),
                ("braco_direito", models.FloatField(blank=True, null=True)),
                ("braco_esquerdo", models.FloatField(blank=True, null=True)),
                ("tricipital", models.FloatField(blank=True, null=True)),
                ("subescapular", models.FloatField(blank=True, null=True)),
                ("axilar_media", models.FloatField(blank=True, null=True)),
                ("suprailiaca", models.FloatField(blank=True, null=True)),
                ("abdominal", models.FloatField(blank=True, null=True)),
                ("coxa", models.FloatField(blank=True, null=True)),
                ("panturrilha", models.FloatField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
