# Generated by Django 5.2.4 on 2025-09-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0023_remove_admin_abdomen_remove_admin_abdominal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="matricula",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="matricula",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="professor",
            name="matricula",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
