# Generated by Django 5.2.4 on 2025-09-12 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "habitusapp",
            "0024_admin_id_aluno_id_professor_id_alter_admin_matricula_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treino",
            name="quant_treinos",
        ),
    ]
