# Generated by Django 5.2.4 on 2025-09-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0025_remove_treino_quant_treinos"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresso",
            name="progresso_valor",
            field=models.IntegerField(default=0),
        ),
    ]
