# Generated by Django 5.2.4 on 2025-09-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0026_progresso_progresso_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresso",
            name="concluidos",
            field=models.IntegerField(default=0),
        ),
    ]
