# Generated by Django 5.2.4 on 2025-09-17 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0027_progresso_concluidos"),
    ]

    operations = [
        migrations.AddField(
            model_name="treino",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habitusapp.professor",
            ),
        ),
    ]
