# Generated by Django 5.2.4 on 2025-09-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0028_treino_professor"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresso",
            name="dias_treinados",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
