# Generated by Django 4.2.7 on 2025-09-18 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitusapp', '0029_progresso_dias_treinados'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresso',
            name='data_entrada',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
