# Generated by Django 5.2.4 on 2025-09-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0030_progresso_data_entrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercicio",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="videos-exercicios/"
            ),
        ),
    ]
