# Generated by Django 5.2.4 on 2025-09-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0031_alter_exercicio_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercicio",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="imagens-exercicios/"
            ),
        ),
    ]
