# Generated by Django 5.2.4 on 2025-09-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0032_exercicio_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treino",
            name="quant_exercicios",
        ),
    ]
