# Generated by Django 5.2.4 on 2025-09-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0033_remove_treino_quant_exercicios"),
    ]

    operations = [
        migrations.AddField(
            model_name="treino",
            name="exercicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habitusapp.exercicio",
            ),
        ),
    ]
