# Generated by Django 5.2.4 on 2025-09-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0035_solicitacaodetreino"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresso",
            name="ultimo_treino_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
