# Generated by Django 5.2.4 on 2025-10-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0036_progresso_ultimo_treino_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="treino",
            name="arquivado",
            field=models.BooleanField(default=False),
        ),
    ]
