# Generated by Django 4.2.7 on 2025-11-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0037_treino_arquivado"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
