# Generated by Django 5.2.4 on 2025-11-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habitusapp", "0038_professor_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("AVISO IMPORTANTE", "Aviso Importante"),
                    ("EVENTO", "Evento"),
                ],
                default="AVISO IMPORTANTE",
                max_length=20,
            ),
        ),
    ]
