from .Exercicio import Exercicio
from .Treino import Treino
from .Aluno import Aluno
from .Professor import Professor
from .Admin import Admin
from .Noticia import Noticia
from .TreinoExercicio import TreinoExercicio
from .Notificacao import Notificacao
from .Progresso import Progresso
from .SolicitacaoDeTreino import SolicitacaoDeTreino
